# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tagent.rpc\"&\n\x12HealthCheckRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\"o\n\x13HealthCheckResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tnode_type\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x03\x12\x0c\n\x04load\x18\x05 \x01(\x01\"k\n\rInvokeRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x13\n\x0bsource_node\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x12\n\ntimeout_ms\x18\x05 \x01(\x05\"T\n\x0eInvokeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\x0c\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x12\n\nelapsed_ms\x18\x04 \x01(\x03\"[\n\rStreamMessage\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x14\n\x0cmessage_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32\xdc\x01\n\x0bNodeService\x12L\n\x0bHealthCheck\x12\x1d.agent.rpc.HealthCheckRequest\x1a\x1e.agent.rpc.HealthCheckResponse\x12=\n\x06Invoke\x12\x18.agent.rpc.InvokeRequest\x1a\x19.agent.rpc.InvokeResponse\x12@\n\x06Stream\x12\x18.agent.rpc.StreamMessage\x1a\x18.agent.rpc.StreamMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=28
  _globals['_HEALTHCHECKREQUEST']._serialized_end=66
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=68
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=179
  _globals['_INVOKEREQUEST']._serialized_start=181
  _globals['_INVOKEREQUEST']._serialized_end=288
  _globals['_INVOKERESPONSE']._serialized_start=290
  _globals['_INVOKERESPONSE']._serialized_end=374
  _globals['_STREAMMESSAGE']._serialized_start=376
  _globals['_STREAMMESSAGE']._serialized_end=467
  _globals['_NODESERVICE']._serialized_start=470
  _globals['_NODESERVICE']._serialized_end=690
# @@protoc_insertion_point(module_scope)
